require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Auto-require default libraries and those for the current Rails environment.
Bundler.require :default, Rails.env

module Rabotnegi
  class Application < Rails::Application
    config.action_controller.cache_store = :file_store, "tmp/cache"
  
    config.gem 'json', :lib => 'json/add/rails'
    config.gem 'will_paginate'
  
    config.time_zone = 'Moscow'

    # config.load_paths += %W( #{config.root}/lib )

    require "lib/ext/core"
    require 'lib/ext/rails'
    require 'lib/ext/libs'
    require 'lib/utilities'
    require 'lib/forms'
  
    config.after_initialize do
      Less::More.header = false
      silence_warnings {
        Less::More::HEADER = %{/* This file was auto generated by Less (http://lesscss.org).\n To change the contents of this file, edit %s instead.*/\n\n}
      }
      
      ActionView::Base.default_form_builder = CustomFormBuilder
      
      ADMIN_LOGIN = 'admin'
      ADMIN_PASSWORD = '0000'      
    end
    
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Add additional load paths for your own custom dirs

    # Only load the plugins named here, in the order given (default is alphabetical).
    # :all can be used as a placeholder for all plugins not explicitly named
    # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

    # Activate observers that should always be running
    # config.active_record.observers = :cacher, :garbage_collector, :forum_observer

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
    # config.i18n.default_locale = :de

    # Configure generators values. Many other options are available, be sure to check the documentation.
    # config.generators do |g|
    #   g.orm             :active_record
    #   g.template_engine :erb
    #   g.test_framework  :test_unit, :fixture => true
    # end

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters << :password    
  end
end
