common: &local_settings
  adapter: mysql
  host: localhost
  encoding: utf8

development:
  <<: *local_settings  
  database: rabotnegi_dev
  username: root

devcache:
  <<: *local_settings
  database: rabotnegi_dev
  username: root

local:
  <<: *local_settings  
  database: rabotnegi_dev
  username: root

test:
  <<: *local_settings  
  database: rabotnegi_test
  username: root
  
staging:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_stg
  username: root
  encoding: utf8

production:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_prod
  username: root
  encoding: utf8
