development:
  adapter: mysql
  host: localhost
  database: rabotnegi_dev
  username: root
  encoding: utf8

test:
  adapter: mysql
  host: localhost
  database: rabotnegi_test
  username: root
  encoding: utf8
  
staging:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_stg
  username: root
  encoding: utf8

production:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_prod
  username: root
  encoding: utf8
