common: &local_settings
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *local_settings  
  database: db/development.sqlite3

devcache:
  <<: *local_settings
  database: db/development.sqlite3

local:
  <<: *local_settings  
  database: db/development.sqlite3

test:
  <<: *local_settings  
  database: db/test.sqlite3

testreal:
  <<: *local_settings  
  database: db/test.sqlite3
  
staging:
  <<: *local_settings  
  database: db/staging.sqlite3

production:
  <<: *local_settings  
  database: db/production.sqlite3
