development:
  adapter: mysql
  database: jobs_dev
  username: root
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: jobs_test
  username: root
  password:
  socket: /tmp/mysql.sock
  encoding: utf8
  
production:
  adapter: mysql
  database: jobs_prod
  username: jobsapp
  password: 123
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8

staging:
  adapter: mysql
  database: jobs_dev
  username: root
  password:
  socket: /tmp/mysql.sock
  encoding: utf8