common: &local_settings
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  encoding: utf8

development:
  <<: *local_settings  
  database: rabotnegi_dev
  username: root

devcache:
  <<: *local_settings
  database: rabotnegi_dev
  username: root

local:
  <<: *local_settings  
  database: rabotnegi_dev
  username: root

test:
  <<: *local_settings  
  database: rabotnegi_test
  username: root
  
staging:
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_stg
  username: root
  password: 0000
  encoding: utf8

production:
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  database: rabotnegi_prod
  username: root
  password: 0000
  encoding: utf8
