development:
  adapter: mysql
  database: jobs_dev
  username: root
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: jobs_test
  username: root
  host: localhost
  encoding: utf8
  
staging:
  adapter: mysql
  database: rabotnegi_stg
  username: root
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8

production:
  adapter: mysql
  database: rabotnegi_prod
  username: root
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8
