RAILS_GEM_VERSION = '2.3.5' unless defined? RAILS_GEM_VERSION
require File.join(File.dirname(__FILE__), 'boot')

Rails::Initializer.run do |config|
  config.action_controller.session = { :session_key => "_jobs_session", :secret => "4b92cb861beba0fa9d81a00f7c427cc23acf164fd9abbd2d542ea4f3352c59f830212504902ba2ab6ad082317e244f8b21c6055e541a618ec485e8f5493f2085" }
  config.action_controller.cache_store = :file_store, "tmp/cache"

  config.gem 'json', :lib => 'json/add/rails'
  config.gem "do_mysql"
  config.gem "dm-core"
  config.gem "dm-validations"
  config.gem "dm-aggregates"
  config.gem "dm-timestamps"

  # config.frameworks -= [ :active_record ]

  config.time_zone = 'Moscow'

  config.after_initialize do
    require 'will_paginate'
    require 'will_paginate/finders/data_mapper'

    require 'ext/core'
    require 'ext/rails'
    require 'ext/libs'
    require 'utilities'
    require 'forms'
    
    Less::More.header = false
    silence_warnings {
      Less::More::HEADER = %{/* This file was auto generated by Less (http://lesscss.org).\n To change the contents of this file, edit %s instead.*/\n\n}
    }
    
    ActionView::Base.default_form_builder = CustomFormBuilder
    
    ADMIN_LOGIN = 'admin'
    ADMIN_PASSWORD = '0000'
  end
end
