RAILS_GEM_VERSION = '2.3.5' unless defined? RAILS_GEM_VERSION
require File.join(File.dirname(__FILE__), 'boot')

Rails::Initializer.run do |config|
  config.action_controller.session = { :session_key => "_jobs_session", :secret => "4b92cb861beba0fa9d81a00f7c427cc23acf164fd9abbd2d542ea4f3352c59f830212504902ba2ab6ad082317e244f8b21c6055e541a618ec485e8f5493f2085" }
 	config.gem 'will_paginate'
  config.gem 'json', :lib => 'json/add/rails'
  config.time_zone = 'Moscow'
  config.action_controller.cache_store = :file_store, "tmp/cache"

  config.after_initialize do
    require 'forwardable'
    require 'ext/core'
    require 'ext/active_record'
    require 'ext/action_controller'
    require 'ext/action_view'
    require 'ext/will_paginate'
    require 'ext/simple_captcha'
    require 'common'
    require 'forms'
    require 'log_helper'
    
    HoptoadNotifier.configure do |config|
      config.api_key = '8b0496b81118139d93e5be18b130a7a8'
    end

    Less::More.header = false
    silence_warnings {
      Less::More::HEADER = %{/* This file was auto generated by Less (http://lesscss.org).\n To change the contents of this file, edit %s instead.*/\n\n}
    }
    
    
    ADMIN_LOGIN = 'admin'
    ADMIN_PASSWORD = '0000'
    
    DB = ActiveRecord::Base.connection
  end
end
