defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: rabotnegi_dev

devcache:
  <<: *defaults
  database: rabotnegi_dev

test:
  <<: *defaults
  database: rabotnegi_test

test_web:
  <<: *defaults
  database: rabotnegi_test_web

test_real:
  <<: *defaults
  database: rabotnegi_test_real

staging:
  host: localhost
  database: rabotnegi_stg

production:
  host: localhost
  database: rabotnegi_prod
