# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "employers", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "login",      :string
    t.column "password",   :string
    t.column "created_at", :datetime,                 :null => false
    t.column "updated_at", :datetime,                 :null => false
  end

  add_index "employers", ["login"], :name => "ix_employers_login", :unique => true

  create_table "resumes", :force => true do |t|
    t.column "fname",        :string,   :limit => 30,                                                                                                                                                                                                                                                                      :default => "", :null => false
    t.column "lname",        :string,   :limit => 30,                                                                                                                                                                                                                                                                      :default => "", :null => false
    t.column "password",     :string,   :limit => 30
    t.column "city",         :enum,     :limit => [:msk, :spb, :ekb, :nn, :nsk],                                                                                                                                                                                                                                                           :null => false
    t.column "job_title",    :string,   :limit => 100,                                                                                                                                                                                                                                                                     :default => "", :null => false
    t.column "industry",     :enum,     :limit => [:it, :finance, :transportation, :logistics, :service, :wholesale, :manufactoring, :restaurant, :retail, :office, :building, :hr, :marketing, :medicine, :realty, :sales, :publishing, :insurance, :telecom, :executives, :hospitality, :telework, :householding, :law],                 :null => false
    t.column "min_salary",   :integer,                                                                                                                                                                                                                                                                                                     :null => false
    t.column "view_count",   :integer,                                                                                                                                                                                                                                                                                     :default => 0,  :null => false
    t.column "job_reqs",     :text
    t.column "about_me",     :text
    t.column "contact_info", :text
    t.column "created_at",   :datetime,                                                                                                                                                                                                                                                                                                    :null => false
    t.column "updated_at",   :datetime,                                                                                                                                                                                                                                                                                                    :null => false
  end

  add_index "resumes", ["lname", "fname"], :name => "ix_resumes_lname_fname"
  add_index "resumes", ["city"], :name => "ix_resumes_city"
  add_index "resumes", ["industry"], :name => "ix_resumes_industry"
  add_index "resumes", ["city", "industry"], :name => "ix_resumes_city_industry"

  create_table "vacancies", :force => true do |t|
    t.column "title",         :string,                                                                                                                                                                                                                                                                                       :default => "", :null => false
    t.column "description",   :text,                                                                                                                                                                                                                                                                                         :default => "", :null => false
    t.column "external_id",   :integer
    t.column "industry",      :enum,      :limit => [:it, :finance, :transportation, :logistics, :service, :wholesale, :manufactoring, :restaurant, :retail, :office, :building, :hr, :marketing, :medicine, :realty, :sales, :publishing, :insurance, :telecom, :executives, :hospitality, :telework, :householding, :law],                 :null => false
    t.column "city",          :enum,      :limit => [:msk, :spb, :ekb, :nn, :nsk],                                                                                                                                                                                                                                                           :null => false
    t.column "salary_min",    :integer
    t.column "salary_max",    :integer
    t.column "employer_id",   :integer
    t.column "employer_name", :string
    t.column "created_at",    :timestamp,                                                                                                                                                                                                                                                                                                    :null => false
    t.column "updated_at",    :timestamp,                                                                                                                                                                                                                                                                                                    :null => false
  end

  add_index "vacancies", ["external_id"], :name => "uq_vacancies_external_id", :unique => true
  add_index "vacancies", ["city"], :name => "ix_vacancies_city"
  add_index "vacancies", ["industry"], :name => "ix_vacancies_industry"
  add_index "vacancies", ["city", "industry"], :name => "ix_vacancies_city_industry"
  add_index "vacancies", ["employer_id"], :name => "fk_vacancies_employers"

end
